language: node_js

node_js:
  - node

script:
  - npm run test:unit

deploy:
  - provider: pages
    local-dir: docs/.vuepress/dist
    skip-cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    email: 1648314523@qq.com
    on:
      branch: master
  - provider: npm
    email: 1648314523@qq.com
    on:
      tags: true
      repo: 3scarecrow/vue-quarter-select
