language: node_js

node_js:
  - node

script:
  - npm run test:unit

deploy:
  - provider: pages
    local-dir: docs/.vuepress/dist
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    email: 1648314523@qq.com
    on:
      branch: master
  - provider: npm
    api_key: $NPM_TOKEN
    email: 1648314523@qq.com
    on:
      tags: true
      repo: 3scarecrow/vue-quarter-select
